// Dummy product data for the e-commerce website
const allProducts = {
    men: [
      {
        id: 1,
        title: "Classic White T-Shirt",
        price: 999,
        category: "mens",
        subcategory: "T-Shirts",
        color: "White",
        image: "images/WHITE-TSHIRT.jpg?height=400&width=300&text=Classic+White+T-Shirt",
      },
      {
        id: 2,
        title: "Slim Fit Blue Jeans",
        price: 2499,
        category: "mens",       
        subcategory: "Jeans",
        color: "Blue",
        image: "images/SLIM-FIT.jpg?height=400&width=300&text=Slim+Fit+Blue+Jeans",
      },
      {
        id: 3,
        title: "Casual Oxford Shirt",
        price: 1499,
        category: "mens",
        subcategory: "Shirts",
        color: "Light Blue",
        image: "images/OXFORD.jpg?height=400&width=300&text=Casual+Oxford+Shirt",
      },
      {
        id: 4,
        title: "Black Denim Jacket",
        price: 2999,
        category: "mens",
        subcategory: "Jackets",
        color: "Black",
        image: "images/BLACK-DENIM.jpg?height=400&width=300&text=Black+Denim+Jacket",
      },
      {
        id: 5,
        title: "Gray Chino Pants",
        price: 1999,
        category: "mens",
        subcategory: "Pants",
        color: "Gray",
        image: "images/CHINO.jpg?height=400&width=300&text=Gray+Chino+Pants",
      },
      {
        id: 6,
        title: "Leather Belt",
        price: 1299,
        category: "mens",
        subcategory: "Accessories",
        color: "Brown",
        image: "images/LEATHER-BELT.jpg?height=400&width=300&text=Leather+Belt",
      },
      {
        id: 7,
        title: "Striped Polo Shirt",
        price: 1499,
        category: "mens",
        subcategory: "T-Shirts",
        color: "Navy",
        image: "images/STRIPED-POLO.jpg?height=400&width=300&text=Striped+Polo+Shirt",
      },
      {
        id: 8,
        title: "Relaxed Fit Jeans",
        price: 2299,
        category: "mens",
        subcategory: "Jeans",
        color: "Dark Blue",
        image: "images/RELAXED-FIT.jpg?height=400&width=300&text=Relaxed+Fit+Jeans",
      },
      {
        id: 9,
        title: "White Dress Shirt",
        price: 1799,
        category: "mens",
        subcategory: "Shirts",
        color: "White",
        image: "images/WHITE-SHIRT.jpg?height=400&width=300&text=White+Dress+Shirt",
      },
      {
        id: 10,
        title: "Bomber Jacket",
        price: 3299,
        category: "mens",
        subcategory: "Jackets",
        color: "Green",
        image: "images/BOMBER.jpg?height=400&width=300&text=Bomber+Jacket",
      },
      {
        id: 11,
        title: "Black Dress Pants",
        price: 2199,
        category: "mens",
        subcategory: "Pants",
        color: "Black",
        image: "images/BLACK-DRESS.jpg?height=400&width=300&text=Black+Dress+Pants",
      },    
      {
        id: 12,
        title: "Leather Wallet",
        price: 1199,
        category: "mens",
        subcategory: "Accessories",
        color: "Brown",
        image: "images/LEATHER-WALLET.jpg?height=400&width=300&text=Leather+Wallet",
      },
      {
        id: 13,
        title: "V-Neck T-Shirt",
        price: 799,
        category: "mens",
        subcategory: "T-Shirts",
        color: "Black",
        image: "images/V-NECK.jpg?height=400&width=300&text=V-Neck+T-Shirt",
      },
      {
        id: 14,
        title: "Slim Black Jeans",
        price: 2499,
        category: "mens",
        subcategory: "Jeans",
        color: "Black",
        image: "images/SLIM-BLACK.jpg?height=400&width=300&text=Slim+Black+Jeans",
      },
      {
        id: 15,
        title: "Plaid Button-Up",
        price: 1499,
        category: "mens",
        subcategory: "Shirts",
        color: "Red",
        image: "images/BUTTON.jpg?height=400&width=300&text=Plaid+Button-Up",
      },
      {
        id: 16,
        title: "Leather Jacket",
        price: 6499,
        category: "mens",
        subcategory: "Jackets",     
        color: "Black",
        image: "images/LEATHER-JACKET.jpg?height=400&width=300&text=Leather+Jacket",
      },
      {
        id: 17,
        title: "Khaki Pants",
        price: 1799,
        category: "mens",
        subcategory: "Pants"  ,
        color: "Beige",
        image: "images/KHAKI.jpg?height=400&width=300&text=Khaki+Pants",
      },
      {
        id: 18,
        title: "Leather Watch",
        price: 2499,
        category: "mens",
        subcategory: "Accessories",
        color: "Brown",
        image: "images/LEATHER-WATCH.jpg?height=400&width=300&text=Leather+Watch",
      },
      {
        id: 19,
        title: "Graphic T-Shirt",
        price: 999,
        category: "mens",
        subcategory: "T-Shirts",
        color: "White",
        image: "images/PRINTED-SHIRT.jpg?height=400&width=300&text=Graphic+T-Shirt",
      },
      {
        id: 20,
        title: "Distressed Jeans",
        price: 2799,
        category: "mens",
        subcategory: "Jeans",
        color: "Blue",
        image: "images/DISTRESSED.jpg?height=400&width=300&text=Distressed+Jeans",
      },
      {
        id: 21,
        title: "Denim Shirt",
        price: 1999,
        category: "mens",
        subcategory: "Shirts",
        color: "Blue",
        image: "images/DENIM.jpg?height=400&width=300&text=Denim+Shirt",
      },
      {
        id: 22,
        title: "Windbreaker",
        price: 2999,               
        category: "mens",
        subcategory: "Jackets",
        color: "Gray",
        image: "images/WINDBREAKER.jpg?height=400&width=300&text=Windbreaker",
      },
      {
        id: 23,
        title: "Cargo Pants",
        price: 2199,
        category: "mens",
        subcategory: "Pants",
        color: "Green",
        image: "images/CARGO.jpg?height=400&width=300&text=Cargo+Pants",
      },
      {
        id: 24,
        title: "Leather Bracelet",
        price: 799,
        category: "mens",
        subcategory: "Accessories",
        color: "Brown",
        image: "images/LEATHER-BRACELET.jpg?height=400&width=300&text=Leather+Bracelet",
      },
    ],
    women: [
      {
        id: 25,
        title: "Floral Summer Dress",
        price: 3499,
        category: "womens",
        subcategory: "Dresses",
        color: "Pink",
        image: "images/FLORAL-SUMMER.jpg?height=400&width=300&text=Floral+Summer+Dress",
      },
      {
        id: 26,
        title: "Classic White Blouse",
        price: 1999,
        category: "womens",
        subcategory: "Tops",
        color: "White",
        image: "images/CLASSIC-WHITE-BLOUSE.jpg?height=400&width=300&text=Classic+White+Blouse",
      },
      {
        id: 27,
        title: "High-Waist Jeans",
        price: 2499,
        category: "womens",
        subcategory: "Pants",
        color: "Blue",
        image: "images/HIGH-WAIST-JEANS.jpg?height=400&width=300&text=High-Waist+Jeans",
      },
      {
        id: 28,
        title: "A-Line Skirt",
        price: 1799,
        category: "womens",
        subcategory: "Skirts",
        color: "Black",
        image: "images/A-LINE-SKIRT.jpg?height=400&width=300&text=A-Line+Skirt",
      },
      {
        id: 29,
        title: "Leather Jacket",
        price: 4999,
        category: "womens",
        subcategory: "Jackets",
        color: "Black",
        image: "images/LEATHER-JACKET.jpg?height=400&width=300&text=Leather+Jacket",
      },
      {
        id: 30,
        title: "Gold Necklace",
        price: 1499,
        category: "womens",
        subcategory: "Accessories",
        color: "Gold",
        image: "images/GOLD-NECKLACE.jpg?height=400&width=300&text=Gold+Necklace",
      },
      {
        id: 31,
        title: "Cocktail Dress",
        price: 3999,
        category: "womens",
        subcategory: "Dresses",
        color: "Black",
        image: "images/COCKTAIL-DRESS.jpg?height=400&width=300&text=Cocktail+Dress",
      },
      {
        id: 32,
        title: "Silk Camisole",
        price: 1299,
        category: "womens",
        subcategory: "Tops",
        color: "White",
        image: "images/SILK-CAMISOLE.jpg?height=400&width=300&text=Silk+Camisole",
      },
      {
        id: 33,
        title: "Wide-Leg Pants",
        price: 2299,
        category: "womens",
        subcategory: "Pants",
        color: "Black",
        image: "images/WIDE-LEG-PANTS.jpg?height=400&width=300&text=Wide-Leg+Pants",
      },
      {
        id: 34,
        title: "Pleated Skirt",
        price: 1699,
        category: "womens",
        subcategory: "Skirts",
        color: "Blue",
        image: "images/PLEATED-SKIRT.jpg?height=400&width=300&text=Pleated+Skirt",
      },
      {
        id: 35,
        title: "Denim Jacket",
        price: 2999,
        category: "womens",
        subcategory: "Jackets",
        color: "Blue",
        image: "images/DENIM-JACKET.jpg?height=400&width=300&text=Denim+Jacket",
      },
      {
        id: 36,
        title: "Pearl Earrings",
        price: 999,
        category: "womens",
        subcategory: "Accessories",
        color: "White",
        image: "images/PERAL-EARRING.jpg?height=400&width=300&text=Pearl+Earrings",
      },
      {
        id: 37,
        title: "Maxi Dress",
        price: 3499,
        category: "womens",
        subcategory: "Dresses",
        color: "Green",
        image: "images/MAXI-DRESS.jpg?height=400&width=300&text=Maxi+Dress",
      },
      {
        id: 38,
        title: "Turtleneck Sweater",
        price: 1999,
        category: "womens",
        subcategory: "Tops",
        color: "Black",
        image: "images/TURTLENECK-SWEATER.jpg?height=400&width=300&text=Turtleneck+Sweater",
      },
      {
        id: 39,
        title: "Culottes",
        price: 2499,
        category: "womens",
        subcategory: "Pants",
        color: "White",
        image: "images/CULOTTES.jpg?height=400&width=300&text=Culottes",
      },
      {
        id: 40,
        title: "Pencil Skirt",
        price: 1999,
        category: "womens",
        subcategory: "Skirts",
        color: "Red",
        image: "images/PENCIL-SKIRT.jpg?height=400&width=300&text=Pencil+Skirt",
      },
      {
        id: 41,
        title: "Blazer",
        price: 3999,
        category: "womens",
        subcategory: "Jackets",
        color: "Black",
        image: "images/BLAZER.jpg?height=400&width=300&text=Blazer",
      },
      {
        id: 42,
        title: "Silk Scarf",
        price: 1499,
        category: "womens",
        subcategory: "Accessories",
        color: "Pink",
        image: "images/SILK-SCRAF.jpg?height=400&width=300&text=Silk+Scarf",
      },
      {
        id: 43,
        title: "Wrap Dress",
        price: 3799,
        category: "womens",
        subcategory: "Dresses",
        color: "Blue",
        image: "images/WRAP-DRESS.jpg?height=400&width=300&text=Wrap+Dress",
      },
      {
        id: 44,
        title: "Lace Top",
        price: 1799,
        category: "womens",
        subcategory: "Tops",
        color: "White",
        image: "images/LACE-TOP.jpg?height=400&width=300&text=Lace+Top",
      },
      {
        id: 45,
        title: "Cargo Pants",
        price: 2499,
        category: "womens",
        subcategory: "Pants",
        color: "Green",
        image: "images/CARGO-PANTS.jpg?height=400&width=300&text=Cargo+Pants",
      },
      {
        id: 46,
        title: "Midi Skirt",
        price: 1799,
        category: "womens",
        subcategory: "Skirts",
        color: "Black",
        image: "images/MIDI-SKIRT.jpg?height=400&width=300&text=Midi+Skirt",
      },
      {
        id: 47,
        title: "Trench Coat",
        price: 5999,
        category: "womens",
        subcategory: "Jackets",
        color: "Beige",
        image: "images/TRENCH-COAT.jpg?height=400&width=300&text=Trench+Coat",
      },
      {
        id: 48,
        title: "Statement Necklace",
        price: 1799,
        category: "womens",
        subcategory: "Accessories",
        color: "Gold",
        image: "images/STATEMENT-NECKLACE.jpg?height=400&width=300&text=Statement+Necklace",
      }
    ],
    kids: [
      {
        id: 49,
        title: "Baby Onesie Set",
        price: 999,
        category: "kids",
        subcategory: "Tops",
        ageGroup: "Baby (0-24 months)",
        color: "Blue",
        image: "images/BABY-SET.jpg?height=400&width=300&text=Baby+Onesie+Set",
      },
      {
        id: 50,
        title: "Toddler Denim Jeans",
        price: 1299,
        category: "kids",
        subcategory: "Bottoms",
        ageGroup: "Toddler (2-4 years)",
        color: "Blue",
        image: "images/TODDLER-DENIM.jpg?height=400&width=300&text=Toddler+Denim+Jeans",
      },
      {
        id: 51,
        title: "Princess Dress",
        price: 1499,
        category: "kids",
        subcategory: "Dresses",
        ageGroup: "Kids (4-7 years)",
        color: "Pink",
        image: "images/PRINCESS-DRESS.jpg?height=400&width=300&text=Princess+Dress",
      },
      {
        id: 52,
        title: "Kids Winter Jacket",
        price: 1999,
        category: "kids",
        subcategory: "Outerwear",
        ageGroup: "Older Kids (8-14 years)",
        color: "Red",
        image: "images/Kids Winter Jacket.jpg?height=400&width=300&text=Kids+Winter+Jacket",
      },
      {
        id: 53,
        title: "Baby Sneakers",
        price: 799,
        category: "kids",
        subcategory: "Shoes",
        ageGroup: "Baby (0-24 months)",
        color: "White",
        image: "images/Baby Sneakers.jpg?height=400&width=300&text=Baby+Sneakers",
      },
      {
        id: 54,
        title: "Kids Backpack",
        price: 999,
        category: "kids",
        subcategory: "Accessories",
        ageGroup: "Older Kids (8-14 years)",
        color: "Blue",
        image: "images/Kids Backpack.jpg?height=400&width=300&text=Kids+Backpack",
      },
      {
        id: 55,
        title: "Toddler T-Shirt Set",
        price: 899,
        category: "kids",
        subcategory: "Tops",
        ageGroup: "Toddler (2-4 years)",
        color: "Yellow",
        image: "images/Toddler T-Shirt Set.jpg?height=400&width=300&text=Toddler+T-Shirt+Set",
      },
      {
        id: 56,
        title: "Kids Cargo Pants",
        price: 1199,
        category: "kids",
        subcategory: "Bottoms",
        ageGroup: "Kids (4-7 years)",
        color: "Green",
        image: "images/Kids Cargo Pants.jpg?height=400&width=300&text=Kids+Cargo+Pants",
      },
      {
        id: 57,
        title: "Tutu Dress",
        price: 1299,
        category: "kids",
        subcategory: "Dresses",
        ageGroup: "Toddler (2-4 years)",
        color: "Purple",
        image: "images/Tutu Dress.jpg?height=400&width=300&text=Tutu+Dress",
      },
      {
        id: 58,
        title: "Kids Rain Jacket",
        price: 1599,
        category: "kids",
        subcategory: "Outerwear",
        ageGroup: "Kids (4-7 years)",
        color: "Yellow",
        image: "images/Kids Rain Jacket.jpg?height=400&width=300&text=Kids+Rain+Jacket",
      },
      {
        id: 59,             
        title: "Toddler Sandals",
        price: 999,
        category: "kids",
        subcategory: "Shoes",
        ageGroup: "Toddler (2-4 years)",
        color: "Blue",
        image: "images/Toddler Sandals.jpg?height=400&width=300&text=Toddler+Sandals",
      },
      {
        id: 60,
        title: "Kids Water Bottle",
        price: 599,
        category: "kids",
        subcategory: "Accessories",
        ageGroup: "Kids (4-7 years)",
        color: "Green",
        image: "images/Kids Water Bottle.jpg?height=400&width=300&text=Kids+Water+Bottle",
      },
      {
        id: 61,
        title: "Baby Romper",
        price: 799,
        category: "kids",
        subcategory: "Tops",
        ageGroup: "Baby (0-24 months)",
        color: "Pink",
        image: "images/Baby Romper.jpg?height=400&width=300&text=Baby+Romper",
      },
      {
        id: 62,
        title: "Kids Shorts Set",
        price: 999,
        category: "kids",
        subcategory: "Bottoms",
        ageGroup: "Older Kids (8-14 years)",
        color: "Blue",
        image: "images/Kids Shorts Set.jpg?height=400&width=300&text=Kids+Shorts+Set",
      },
      {
        id: 63,
        title: "Party Dress",
        price: 1599,
        category: "kids",
        subcategory: "Dresses",
        ageGroup: "Kids (4-7 years)",
        color: "Purple",
        image: "images/Party Dress.jpg?height=400&width=300&text=Party+Dress",
      },
      {
        id: 64,
        title: "Kids Hoodie",
        price: 1499,
        category: "kids",
        subcategory: "Outerwear",
        ageGroup: "Older Kids (8-14 years)",
        color: "Red",
        image: "images/Kids Hoodie.jpg?height=400&width=300&text=Kids+Hoodie",
      },
      {
        id: 65,
        title: "Kids Running Shoes",
        price: 1799,
        category: "kids",
        subcategory: "Shoes",
        ageGroup: "Kids (4-7 years)",
        color: "Black",
        image: "images/Kids Running Shoes.jpg?height=400&width=300&text=Kids+Running+Shoes",
      },
      {
        id: 66,
        title: "Kids Lunch Box",
        price: 799,
        category: "kids",
        subcategory: "Accessories",
        ageGroup: "Older Kids (8-14 years)",
        color: "Blue",
        image: "images/Kids Lunch Box.jpg?height=400&width=300&text=Kids+Lunch+Box",
      },
      {
        id: 67,
        title: "Baby Sleepwear Set",
        price: 899,
        category: "kids",
        subcategory: "Tops",
        ageGroup: "Baby (0-24 months)",
        color: "White",
        image: "images/Baby Sleepwear Set.jpg?height=400&width=300&text=Baby+Sleepwear+Set",
      },
      {
        id: 68,
        title: "Toddler Sweatpants",
        price: 999,
        category: "kids",
        subcategory: "Bottoms",
        ageGroup: "Toddler (2-4 years)",
        color: "Gray",
        image: "images/Toddler Sweatpants.jpg?height=400&width=300&text=Toddler+Sweatpants",
      },
      {
        id: 69,
        title: "Summer Dress",
        price: 1199,
        category: "kids",
        subcategory: "Dresses",
        ageGroup: "Toddler (2-4 years)",
        color: "Yellow",
        image: "images/Summer Dress.jpg?height=400&width=300&text=Summer+Dress",
      },
      {
        id: 70,
        title: "Kids Puffer Jacket",
        price: 2199,
        category: "kids",
        subcategory: "Outerwear",
        ageGroup: "Kids (4-7 years)",
        color: "Green",     
        image: "images/Kids Puffer Jacket.jpg?height=400&width=300&text=Kids+Puffer+Jacket",
      },
      {
        id: 71,
        title: "Kids Soccer Cleats",
        price: 1599,
        category: "kids",
        subcategory: "Shoes",
        ageGroup: "Older Kids (8-14 years)",
        color: "Black",
        image: "images/Kids Soccer Cleats.jpg?height=400&width=300&text=Kids+Soccer+Cleats",
      },
      {
        id: 72,
        title: "Kids Baseball Cap",
        price: 699,
        category: "kids",
        subcategory: "Accessories",
        ageGroup: "Kids (4-7 years)",
        color: "Blue",
        image: "images/Kids Baseball Cap.jpg?height=400&width=300&text=Kids+Baseball+Cap",
      }
    ],
    skincare: [
      {
        id: 73,
        title: "Gentle Foaming Cleanser",
        price: 999,
        category: "skincare",
        subcategory: "Cleansers",
        skinType: "All Skin Types",
        concern: "Hydration",
        image: "images/Gentle Foaming Cleanser.jpg?height=400&width=300&text=Gentle+Foaming+Cleanser",
      },
      {
        id: 74,
        title: "Hydrating Moisturizer",
        price: 1299,
        category: "skincare",
        subcategory: "Moisturizers",
        skinType: "Dry",
        concern: "Hydration",
        image: "images/Hydrating Moisturizer.jpg?height=400&width=300&text=Hydrating+Moisturizer",
      },
      {
        id: 75,
        title: "Vitamin C Serum",
        price: 1999,
        category: "skincare",
        subcategory: "Serums",
        skinType: "All Skin Types",
        concern: "Brightening",
        image: "images/Vitamin C Serum.jpg?height=400&width=300&text=Vitamin+C+Serum",
      },
      {
        id: 76,
        title: "Clay Face Mask",
        price: 799,
        category: "skincare",
        subcategory: "Masks",
        skinType: "Oily",
        concern: "Pores",
        image: "images/Clay Face Mask.jpg?height=400&width=300&text=Clay+Face+Mask",
      },
      {
        id: 77,
        title: "SPF 50 Sunscreen",
        price: 1499,
        category: "skincare",
        subcategory: "Sunscreen",
        skinType: "All Skin Types",
        concern: "Anti-Aging",
        image: "images/SPF 50 Sunscreen.jpg?height=400&width=300&text=SPF+50+Sunscreen",
      },
      {
        id: 78,
        title: "Retinol Treatment",
        price: 2499,
        category: "skincare",
        subcategory: "Treatments",
        skinType: "Combination",
        concern: "Anti-Aging",
        image: "images/Retinol Treatment.jpg?height=400&width=300&text=Retinol+Treatment",
      },
      {
        id: 79,
        title: "Oil-Free Cleanser",
        price: 899,
        category: "skincare",
        subcategory: "Cleansers",
        skinType: "Oily",
        concern: "Acne",
        image: "images/Oil-Free Cleanser.jpg?height=400&width=300&text=Oil-Free+Cleanser",
      },
      {
        id: 80,
        title: "Rich Night Cream",
        price: 1599,
        category: "skincare",
        subcategory: "Moisturizers",
        skinType: "Dry",
        concern: "Hydration",
        image: "images/Rich Night Cream.jpg?height=400&width=300&text=Rich+Night+Cream",
      },
      {
        id: 81,
        title: "Hyaluronic Acid Serum",
        price: 1799,
        category: "skincare",
        subcategory: "Serums",
        skinType: "All Skin Types", 
        concern: "Hydration",
        image: "images/Hyaluronic Acid Serum.jpg?height=400&width=300&text=Hyaluronic+Acid+Serum",
      },
      {
        id: 82,
        title: "Sheet Mask Set",
        price: 999,
        category: "skincare",
        subcategory: "Masks",
        skinType: "All Skin Types",
        concern: "Brightening",
        image: "images/Sheet Mask Set.jpg?height=400&width=300&text=Sheet+Mask+Set",
      },
      {
        id: 83,
        title: "Mineral Sunscreen",
        price: 1299,
        category: "skincare",
        subcategory: "Sunscreen",
        skinType: "Sensitive",
        concern: "Redness",
        image: "images/Mineral Sunscreen.jpg?height=400&width=300&text=Mineral+Sunscreen",
      },
      {
        id: 84,
        title: "Salicylic Acid Treatment",
        price: 1099,
        category: "skincare",
        subcategory: "Treatments",
        skinType: "Oily",
        concern: "Acne",
        image: "images/Salicylic Acid Treatment.jpg?height=400&width=300&text=Salicylic+Acid+Treatment",
      },
      {
        id: 85,
        title: "Creamy Cleanser",
        price: 1099,
        category: "skincare",
        subcategory: "Cleansers",
        skinType: "Dry",
        concern: "Hydration",
        image: "images/Creamy Cleanser.jpg?height=400&width=300&text=Creamy+Cleanser",
      },
      {
        id: 86,
        title: "Gel Moisturizer",
        price: 1399,
        category: "skincare",
        subcategory: "Moisturizers",
        skinType: "Oily",
        concern: "Pores",
        image: "images/Gel Moisturizer.jpg?height=400&width=300&text=Gel+Moisturizer",
      },
      {
        id: 87,
        title: "Niacinamide Serum",
        price: 1599,
        category: "skincare",
        subcategory: "Serums",
        skinType: "Combination",
        concern: "Pores",
        image: "images/Niacinamide Serum.jpg?height=400&width=300&text=Niacinamide+Serum",
      },
      {
        id: 88,
        title: "Sleeping Mask",
        price: 1499,
        category: "skincare",
        subcategory: "Masks",
        skinType: "All Skin Types",
        concern: "Hydration",
        image: "images/Sleeping Mask.jpg?height=400&width=300&text=Sleeping+Mask",
      },
      {
        id: 89,
        title: "Tinted Sunscreen",
        price: 1599,
        category: "skincare",
        subcategory: "Sunscreen",
        skinType: "All Skin Types",
        concern: "Anti-Aging",
        image: "images/Tinted Sunscreen.jpg?height=400&width=300&text=Tinted+Sunscreen",
      },
      {
        id: 90,
        title: "Spot Treatment",
        price: 799,
        category: "skincare",
        subcategory: "Treatments",
        skinType: "Oily",
        concern: "Acne",
        image: "images/Spot Treatment.jpg?height=400&width=300&text=Spot+Treatment",
      },
      {
        id: 91,
        title: "Micellar Water",
        price: 899,
        category: "skincare",
        subcategory: "Cleansers",
        skinType: "Sensitive",
        concern: "Redness",
        image: "images/Micellar Water.jpg?height=400&width=300&text=Micellar+Water",
      },
      {
        id: 92,
        title: "Barrier Repair Cream",
        price: 1799,
        category: "skincare",
        subcategory: "Moisturizers",
        skinType: "Sensitive",
        concern: "Redness",
        image: "images/Barrier Repair Cream.jpg?height=400&width=300&text=Barrier+Repair+Cream",
      },
      {
        id: 93,
        title: "Peptide Serum",
        price: 2199,
        category: "skincare",
        subcategory: "Serums",
        skinType: "All Skin Types",
        concern: "Anti-Aging",
        image: "images/Peptide Serum.jpg?height=400&width=300&text=Peptide+Serum",
      },
      {
        id: 94,
        title: "Charcoal Mask",
        price: 1099,
        category: "skincare",
        subcategory: "Masks",
        skinType: "Combination",
        concern: "Pores",
        image: "images/Charcoal Mask.jpg?height=400&width=300&text=Charcoal+Mask",
      },
      {
        id: 95,
        title: "Sport Sunscreen",
        price: 1399,
        category: "skincare",
        subcategory: "Sunscreen",
        skinType: "All Skin Types",
        concern: "Anti-Aging",
        image: "images/Sport Sunscreen.jpg?height=400&width=300&text=Sport+Sunscreen",
      },
      {
        id: 96,
        title: "Brightening Treatment",
        price: 1899,
        category: "skincare",
        subcategory: "Treatments",  
        skinType: "All Skin Types",
        concern: "Brightening",
        image: "images/Brightening Treatment.jpg?height=400&width=300&text=Brightening+Treatment",
      }
    ],
  }
  
  // Function to get random products from a specific category or all categories
  function getRandomProducts(count, tag = null) {
    let productPool =[]
  
    // Combine all products from all categories
    Object.values(allProducts).forEach((categoryProducts) => {
      productPool = [...productPool, ...categoryProducts]
    })
  
    // Filter by tag if provided
    if (tag === "new") {
      // Simulate new arrivals by taking products with higher IDs
      productPool = productPool.filter((product) => {
        const idNumber = Number.parseInt(product.id.split("-")[1])
        return idNumber > 15
      })
    } else if (tag === "bestseller") {
      // Simulate bestsellers by taking products with higher ratings
      productPool = productPool.filter((product) => product.rating >= 4.6)
    }
  
    // Shuffle array
    productPool = productPool.sort(() => 0.5 - Math.random())
  
    // Return requested number of products
    return productPool.slice(0, count)
  }
  
  // Function to get products for a specific category
  function getCategoryProducts(category, count = 24) {
    if (allProducts[category]) {
      return allProducts[category].slice(0, count)
    }
    return []
  }
  
  // Function to get product details by ID
  function getProductById(productId) {
    for (const category in allProducts) {
      const product = allProducts[category].find((p) => p.id === productId)
      if (product) {
        return product
      }
    }
    return null
  }
  
  